/* Generated By:JJTree: Do not edit this line. Root.java */

package wdb.parser;

public class Root extends SimpleNode {
  public Root(int id) {
    super(id);
  }

  public Root(QueryParser p, int id) {
    super(p, id);
  }

}
