language: java

jdk:
    - oraclejdk8

sudo: required

# before_install:
#   - sudo rm -rf /var/lib/cassandra/*
#   - wget http://apache.spinellicreations.com/cassandra/2.1.14/apache-cassandra-2.1.14-bin.tar.gz && tar -xvzf apache-cassandra-2.1.14-bin.tar.gz && sudo sh apache-cassandra-2.1.14/bin/cassandra

before_script:
    - cd jyhton
    - export INSTALLATION_ROOT="."
    - uname -a
    - printenv

script:
    - pwd
    - jdk_switcher use oraclejdk7
    - ant antlr_gen
    - jdk_switcher use oraclejdk8
    - ant

# after_script:
#     - export INSTALLATION_ROOT="."
#     - dist/bin/jython nativeSIMunitTests.py
#     - dist/bin/jython ReLUnitTests.py
#     - dist/bin/jython SPARQLUnitTests.py
#     - ./titan_sim_native_test.sh
