/* Generated By:JJTree: Do not edit this line. False.java */

package wdb.parser;

public class False extends SimpleNode {
  public False(int id) {
    super(id);
  }

  public False(QueryParser p, int id) {
    super(p, id);
  }

}
