/* Generated By:JJTree&JavaCC: Do not edit this line. QueryParserConstants.java */
package wdb.parser;

public interface QueryParserConstants {

  int EOF = 0;
  int LP = 6;
  int RP = 7;
  int LB = 8;
  int RB = 9;
  int COLON = 10;
  int SC = 11;
  int COMMA = 12;
  int CLASS = 13;
  int SUBCLASS = 14;
  int OF = 15;
  int INVERSE = 16;
  int INSERT = 17;
  int INCLUDE = 18;
  int EXCLUDE = 19;
  int WITH = 20;
  int ASSN = 21;
  int SV = 22;
  int MV = 23;
  int REQUIRED = 24;
  int RETRIEVE = 25;
  int WHERE = 26;
  int FROM = 27;
  int AND = 28;
  int OR = 29;
  int NOT = 30;
  int GT = 31;
  int LT = 32;
  int EQ = 33;
  int GTE = 34;
  int LTE = 35;
  int NEQ = 36;
  int TRUE = 37;
  int FALSE = 38;
  int INT = 39;
  int REAL = 40;
  int CHAR = 41;
  int BOOLEAN = 42;
  int STRING = 43;
  int ASTERISK = 44;
  int SOURCE = 45;
  int INDEX = 46;
  int ON = 47;
  int UNIQUE = 48;
  int DISTINCT = 49;
  int MAX = 50;
  int QUIT = 51;
  int MODIFY = 52;
  int LIMIT = 53;
  int ALL = 54;
  int INITIALVALUE = 55;
  int INTEGER = 56;
  int IDENTIFIER = 57;
  int LSTRING = 58;
  int QSTRING = 59;
  int ERROR = 60;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"CLASS\"",
    "\"SUBCLASS\"",
    "\"OF\"",
    "\"INVERSE IS\"",
    "\"INSERT\"",
    "\"INCLUDE\"",
    "\"EXCLUDE\"",
    "\"WITH\"",
    "\":=\"",
    "<SV>",
    "<MV>",
    "\"REQUIRED\"",
    "\"RETRIEVE\"",
    "\"WHERE\"",
    "\"FROM\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\">=\"",
    "\"<=\"",
    "\"<>\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"INTEGER\"",
    "\"REAL\"",
    "\"CHAR\"",
    "\"BOOLEAN\"",
    "\"STRING\"",
    "\"*\"",
    "\"SOURCE\"",
    "\"INDEX\"",
    "\"ON\"",
    "\"UNIQUE\"",
    "\"DISTINCT\"",
    "\"MAX\"",
    "\"QUIT\"",
    "\"MODIFY\"",
    "\"LIMIT\"",
    "\"ALL\"",
    "\"INITIALVALUE\"",
    "<INTEGER>",
    "<IDENTIFIER>",
    "<LSTRING>",
    "<QSTRING>",
    "<ERROR>",
  };

}
