/* Generated By:JJTree: Do not edit this line. Or.java */

package wdb.parser;

public class Or extends SimpleNode {
  public Or(int id) {
    super(id);
  }

  public Or(QueryParser p, int id) {
    super(p, id);
  }

}
