/* Generated By:JJTree: Do not edit this line. True.java */

package wdb.parser;

public class True extends SimpleNode {
  public True(int id) {
    super(id);
  }

  public True(QueryParser p, int id) {
    super(p, id);
  }

}
