/* Generated By:JJTree: Do not edit this line. And.java */

package org.python.ReL.WDB.parser.javacc;

public class And extends SimpleNode {
  public And(int id) {
    super(id);
  }

  public And(QueryParser p, int id) {
    super(p, id);
  }

}
