/* Generated By:JJTree: Do not edit this line. Not.java */

package org.python.ReL.WDB.parser.javacc;

public class Not extends SimpleNode {
  public Not(int id) {
    super(id);
  }

  public Not(QueryParser p, int id) {
    super(p, id);
  }

}
