/* Generated By:JJTree: Do not edit this line. Or.java */

package org.python.ReL.WDB.parser.javacc;

public class Or extends SimpleNode {
  public Or(int id) {
    super(id);
  }

  public Or(QueryParser p, int id) {
    super(p, id);
  }

}
