/* Generated By:JJTree: Do not edit this line. Root.java */

package org.python.ReL.WDB.parser.javacc;

public class Root extends SimpleNode {
  public Root(int id) {
    super(id);
  }

  public Root(QueryParser p, int id) {
    super(p, id);
  }

}
