/* Generated By:JJTree: Do not edit this line. True.java */

package org.python.ReL.WDB.parser.javacc;

public class True extends SimpleNode {
  public True(int id) {
    super(id);
  }

  public True(QueryParser p, int id) {
    super(p, id);
  }

}
