/* Generated By:JJTree: Do not edit this line. And.java */

package wdb.parser;

public class And extends SimpleNode {
  public And(int id) {
    super(id);
  }

  public And(QueryParser p, int id) {
    super(p, id);
  }

}
