/* Generated By:JJTree: Do not edit this line. Cond.java */

package wdb.parser;

public class Cond extends SimpleNode {
  public Cond(int id) {
    super(id);
  }

  public Cond(QueryParser p, int id) {
    super(p, id);
  }

}
